// packages/nuxt/components/TodoList.vue
<script setup lang="ts">
import type { ITodo } from '@todo-list/next/utils/types'
import { stat } from 'fs'
const prefix = 'http://127.0.0.1:3000/api'

const {
  data: initialTodos,
  pending,
  error,
} = await useFetch<ITodo[], any>(`${prefix}/todos`)

const state = reactive({
  hideFinish: false,
  todos: initialTodos.value ?? [],
  text: '',
})
const todosView = computed(() => {
  if (state.hideFinish) {
    return state.todos.filter((todo) => !todo.finish)
  }
  return state.todos
})
const inputRef = ref<HTMLInputElement | null>(null)
async function addTodo() {
  const text = inputRef.value?.value
  if (text) {
    const newTodo = await $fetch<ITodo>(`${prefix}/todos`, {
      method: 'POST',
      body: JSON.stringify({ text }),
    })
    state.todos.unshift(newTodo)
    state.text = ''
    inputRef.value?.focus()
  }
}
async function onFinish(index: number, finish: ITodo['finish']) {
  const todo = state.todos[index]
  const newTodo: ITodo = await $fetch(`${prefix}/todos/${todo.id}`, {
    method: 'PATCH',
    body: JSON.stringify({
      finish: !finish,
      id: todo.id,
    }),
  })
  state.todos[index] = newTodo
}
async function onDelete(id: number) {
  await $fetch(`${prefix}/todos/${id}`, {
    method: 'DELETE',
  })
  state.todos = state.todos.filter((todo) => todo.id !== id)
}
</script>
<template>
  <div className="h-screen text-center">
    <div className="flex justify-center">
      <label className="cursor-pointer pl-16">
        <input
          class="border text-gray-800 border-gray-700 border-r-0 px-4 py-2 rounded-l-md"
          ref="inputRef"
          @keyup.enter="addTodo"
          type="text"
          v-model="state.text"
        />
        <button
          class="border border-gray-700 border-l-0 bg-green-600 dark:bg-green-800 rounded-r-md text-white px-4 py-2"
          @click="addTodo"
        >
          Add Todo
        </button>
      </label>
      <button
        class="w-20 py-2 text-white bg-green-600 dark:bg-green-800 rounded-md ml-4"
        @click="state.hideFinish = !state.hideFinish"
      >
        {{ state.hideFinish ? 'Show' : 'Hide' }}
      </button>
      <ul>
        <li @click="" v-for="(todo, index) in todosView" :key="todo.id">
          <label class="cursor-pointer">
            <input
              type="checkbox"
              name="todo"
              :checked="todo.finish"
              @change="onFinish(index, todo.finish)"
            />
            <span class="{textClassName}">{{ todo.text }}</span>
          </label>
          <button @click="onDelete(todo.id)">删除</button>
        </li>
      </ul>
    </div>
  </div>
</template>

// packages/next/app/todo-list/todo-list.tsx
'use client'
import type { ITodo } from '../../utils/types'
import TodoItem from './todo'
import AddTodo from './add-todo'
import { useMemo, useState } from 'react'
import { queryAddTodo, queryChangeTodo, queryDeleteTodo } from './server'

export default function TodoList({
  initialList = [],
}: {
  initialList: ITodo[]
}) {
  const [list, setList] = useState(initialList)
  const [hideFinish, setHideFinish] = useState(false)
  const filterList = useMemo(() => {
    if (hideFinish) {
      return list.filter((todo) => !todo.finish)
    }
    return list
  }, [list, hideFinish])

  async function onFinish(id: number, finish: boolean) {
    const newTodo = await queryChangeTodo({ id, finish })
    setList(
      list.map((todo) => {
        return todo.id === id ? newTodo : todo
      }),
    )
  }
  async function onAdd(value: string): Promise<boolean> {
    try {
      const newTodo = await queryAddTodo(value)
      setList([newTodo, ...list])
      return true
    } catch (error) {
      return false
    }
  }
  async function onDelete(id: number): Promise<boolean> {
    try {
      await queryDeleteTodo(id)
      setList(list.filter((todo) => todo.id !== id))
      return true
    } catch (error) {
      return false
    }
  }

  return (
    <div className="h-screen text-center">
      <div className="flex justify-center">
        <AddTodo onAdd={onAdd} />
        <button
          className="w-20 py-2 text-white bg-green-600 dark:bg-green-800 rounded-md ml-4"
          onClick={() => setHideFinish(!hideFinish)}
        >
          {hideFinish ? 'Show' : 'Hide'}
        </button>
      </div>
      <ul>
        {filterList.map((todo) => (
          <TodoItem
            key={todo.id}
            todo={todo}
            onFinish={onFinish}
            onDelete={onDelete}
          />
        ))}
      </ul>
    </div>
  )
}
